version: '3.1'

networks:
  thebytecloud:
    driver: bridge
    ipam:
      config:
        - subnet: 181.20.0.0/24

services:
  chennai-node1:
    build:
      context: .
      dockerfile: hazelcast-wan-demo.docker
    image: thebytecloud/hazelcast-wan-demo:latest
    container_name: chennai-node1
    ports:
      - "8081:8080"
    environment:
      - BIND_PORT=8080
    volumes:
      - "./hazelcast-chennai.xml:/hazelcast.xml"
    networks:
      thebytecloud:
        ipv4_address: 181.20.0.3

  mumbai-node1:
    build:
      context: .
      dockerfile: hazelcast-wan-demo.docker
    image: thebytecloud/hazelcast-wan-demo:latest
    container_name: mumbai-node1
    ports:
      - "8082:8080"
    environment:
      - BIND_PORT=8080
    volumes:
      - "./hazelcast-mumbai.xml:/hazelcast.xml"
    networks:
      thebytecloud:
        ipv4_address: 181.20.0.4


